In [5]:
import pandas as pd

In [3]:
df = pd.read_json("https://mallonbacka-dropbox.s3.amazonaws.com/187k_tweets.json", lines=True)
df.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1440519973869260814,1440514991749156864,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,745724702,_marisosa,Chonitaüòó,,...,,,,,,"[{'screen_name': 'edgargarzachave', 'name': 'E...",,,,
1,1440519973776941066,1440519973776941056,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,154734888,kokkozambrano,Jorge Zambrano,,...,,,,,,[],,,,
2,1440519973705711623,1440117598457315328,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,434634968,reereebos,Thighland Resident,,...,,,,,,"[{'screen_name': 'beejoeshay', 'name': '„Çπ„Ç≠„ÉÉ„Éâ',...",,,,
3,1440519973659574275,1440519973659574272,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,1368936153437642757,skellewe,üå∏ Skell ‡´ÆÀÉÃµ÷ä ÀÇÃµ ·Éê,,...,,,,,,[],,,,
4,1440519973609242628,1440456923707424768,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,813245849417515008,alex_k_89,Alex,,...,,,,,,"[{'screen_name': 'Chuck_zw', 'name': 'StandFor...",,,,

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187077 entries, 0 to 187076
Data columns (total 36 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               187077 non-null  int64
 1   conversation_id  187077 non-null  int64
 2   created_at       187077 non-null  datetime64[ns, UTC]
 3   date             187077 non-null  datetime64[ns]
 4   time             187077 non-null  object
 5   timezone         187077 non-null  int64
 6   user_id          187077 non-null  int64
 7   username         187077 non-null  object
 8   name             187077 non-null  object
 9   place            187077 non-null  object
 10  tweet            187077 non-null  object
 11  language         187077 non-null  object
 12  mentions         187077 non-null  object
 13  urls             187077 non-null  object
 14  photos           187077 non-null  object
 15  replies_count    187077 non-null  int64
 16  retweets_count   187077 non-null  int64
 17  likes_count      187077 non-null  int64
 18  hashtags         187077 non-null  object
 19  cashtags         187077 non-null  object
 20  link             187077 non-null  object
 21  retweet          187077 non-null  bool
 22  quote_url        187077 non-null  object
 23  video            187077 non-null  int64
 24  thumbnail        187077 non-null  object
 25  near             187077 non-null  object
 26  geo              187077 non-null  object
 27  source           187077 non-null  object
 28  user_rt_id       187077 non-null  object
 29  user_rt          187077 non-null  object
 30  retweet_id       187077 non-null  object
 31  reply_to         187077 non-null  object
 32  retweet_date     187077 non-null  object
 33  translate        187077 non-null  object
 34  trans_src        187077 non-null  object
 35  trans_dest       187077 non-null  object
dtypes: bool(1), datetime64[ns, UTC](1), datetime64[ns](1), int64(8), object(25)
memory usage: 50.1+ MB

In [10]:
df.shape

(187077, 36)

In [13]:
df.isna().sum()

id                 0
conversation_id    0
created_at         0
date               0
time               0
timezone           0
user_id            0
username           0
name               0
place              0
tweet              0
language           0
mentions           0
urls               0
photos             0
replies_count      0
retweets_count     0
likes_count        0
hashtags           0
cashtags           0
link               0
retweet            0
quote_url          0
video              0
thumbnail          0
near               0
geo                0
source             0
user_rt_id         0
user_rt            0
retweet_id         0
reply_to           0
retweet_date       0
translate          0
trans_src          0
trans_dest         0
dtype: int64

In [23]:
dgeo = pd.DataFrame(df,columns=['geo',  'user_rt',  'user_rt_id'])

In [24]:
dgeo

       geo user_rt user_rt_id
0
1
2
3
4
...     ..     ...        ...
187072
187073
187074
187075
187076

[187077 rows x 3 columns]

As you see , those columns have missing values, but they aren't detected??

In [35]:
df.to_csv (r'C:\Users\h\Desktop\DS project\export_dataframe.csv', index = False, header=True)

I loaded the dataframe into a csv file, then i read it with specifiying a list of a missing values

In [67]:
missing_values = [" ","Nan",'']

In [96]:
data = pd.read_csv("export_dataframe.csv", na_values = missing_values)

In [97]:
data.isna().sum()

id                      0
conversation_id         0
created_at              0
date                    0
time                    0
timezone                0
user_id                 0
username                1
name                    6
place              186651
tweet                   0
language                0
mentions                0
urls                    0
photos                  0
replies_count           0
retweets_count          0
likes_count             0
hashtags                0
cashtags                0
link                    0
retweet                 0
quote_url          166464
video                   0
thumbnail          161265
near                    0
geo                187077
source             187077
user_rt_id         187077
user_rt            187077
retweet_id         187077
reply_to                0
retweet_date       187077
translate          187077
trans_src          187077
trans_dest         187077
dtype: int64

Finally , the missing values are detected, as you can see , there are many columns with only missing values, and also some columns with a LOT of missing values, we should then drop them since they are useless and won't give us any relevent information

In [98]:
data = data.drop(columns =['geo', 'source','user_rt_id','user_rt','retweet_id','retweet_date','translate','trans_src','trans_dest','quote_url','place','thumbnail'], axis = 1)

In [99]:
data.shape

(187077, 24)

In [100]:
data

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,tweet,...,replies_count,retweets_count,likes_count,hashtags,cashtags,link,retweet,video,near,reply_to
0,1440519973869260814,1440514991749156864,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,745724702,_marisosa,Chonitaüòó,@edgargarzachave Pues amos a buscar una skul,...,0,0,0,[],[],https://twitter.com/_marisosa/status/144051997...,False,0,US,"[{'screen_name': 'edgargarzachave', 'name': 'E..."
1,1440519973776941066,1440519973776941056,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,154734888,kokkozambrano,Jorge Zambrano,Algunos decretan‚Ä¶ en mi caso yo concreto! #,...,1,0,2,[],[],https://twitter.com/KOKKOZAMBRANO/status/14405...,False,0,US,[]
2,1440519973705711623,1440117598457315328,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,434634968,reereebos,Thighland Resident,@beejoeshay @Lazce @Miss_Tanie @goth_inthesun ...,...,0,0,12,[],[],https://twitter.com/ReeReeBos/status/144051997...,False,0,US,"[{'screen_name': 'beejoeshay', 'name': '„Çπ„Ç≠„ÉÉ„Éâ',..."
3,1440519973659574275,1440519973659574272,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,1368936153437642757,skellewe,üå∏ Skell ‡´ÆÀÉÃµ÷ä ÀÇÃµ ·Éê,"As√≠ vi a Liz diciendo ""pixelitos"" https://t.c...",...,1,0,2,[],[],https://twitter.com/skellewe/status/1440519973...,False,1,US,[]
4,1440519973609242628,1440456923707424768,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,0,813245849417515008,alex_k_89,Alex,@Chuck_zw @MaximeBernier I'm going to post thi...,...,0,1,3,[],[],https://twitter.com/Alex_K_89/status/144051997...,False,0,US,"[{'screen_name': 'Chuck_zw', 'name': 'StandFor..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187072,1440514731471634441,1437961867054379008,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,0,35020995,shamgarreport,Terry McDermott,@ClearLikeWater1 @nwa @Jeez215 @AustinIdol @ty...,...,0,1,2,[],[],https://twitter.com/shamgarreport/status/14405...,False,0,US,"[{'screen_name': 'ClearLikeWater1', 'name': 'J..."
187073,1440514731450634243,1440514731450634240,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,0,1119277376108683264,clankapp,ClankApp - Crypto Whales Tracker üê≥,"üí∞25,216 #BSV (3,473,860 USD) move from multipl...",...,0,0,0,"['bsv', 'bitcoinsv', 'bsv']",[],https://twitter.com/ClankApp/status/1440514731...,False,0,US,[]
187074,1440514731400302601,1440511169874169856,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,0,251582751,ahedog,german ahedo,@DeMemoria Sue√±os de fuga,...,0,0,0,[],[],https://twitter.com/AhedoG/status/144051473140...,False,0,US,"[{'screen_name': 'DeMemoria', 'name': 'DeMemor..."
187075,1440514731379355649,1440397766027464704,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,0,1258972328970481665,99problmsince99,üß∏,@tujefateama same bro,...,0,0,0,[],[],https://twitter.com/99problmsince99/status/144...,False,0,US,"[{'screen_name': 'tujefateama', 'name': 'la ma..."
187076,1440514731354177536,1440298876057964544,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,0,1171030345732493312,carlosg85040080,Carlos Gutierrez Salcedo,@Pajaropolitico @Conacyt_MX Y ahora cuales son...,...,0,0,0,[],[],https://twitter.com/CarlosG85040080/status/144...,False,0,US,"[{'screen_name': 'Pajaropolitico', 'name': 'An..."

In [101]:
data['timezone'].unique()

array([0], dtype=int64)

also the column timezone contain only 0 as value , so we should drop it too

In [102]:
data = data.drop(columns= 'timezone')

In [103]:
data.shape

(187077, 23)

In [104]:
data['retweet'].unique()

array([False])

In [105]:
data = data.drop(columns = 'retweet')

In [106]:
data.shape

(187077, 22)

In [107]:
data

,id,conversation_id,created_at,date,time,user_id,username,name,tweet,language,...,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,link,video,near,reply_to
0,1440519973869260814,1440514991749156864,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,745724702,_marisosa,Chonitaüòó,@edgargarzachave Pues amos a buscar una skul,es,...,[],0,0,0,[],[],https://twitter.com/_marisosa/status/144051997...,0,US,"[{'screen_name': 'edgargarzachave', 'name': 'E..."
1,1440519973776941066,1440519973776941056,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,154734888,kokkozambrano,Jorge Zambrano,Algunos decretan‚Ä¶ en mi caso yo concreto! #,es,...,[],1,0,2,[],[],https://twitter.com/KOKKOZAMBRANO/status/14405...,0,US,[]
2,1440519973705711623,1440117598457315328,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,434634968,reereebos,Thighland Resident,@beejoeshay @Lazce @Miss_Tanie @goth_inthesun ...,en,...,[],0,0,12,[],[],https://twitter.com/ReeReeBos/status/144051997...,0,US,"[{'screen_name': 'beejoeshay', 'name': '„Çπ„Ç≠„ÉÉ„Éâ',..."
3,1440519973659574275,1440519973659574272,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,1368936153437642757,skellewe,üå∏ Skell ‡´ÆÀÉÃµ÷ä ÀÇÃµ ·Éê,"As√≠ vi a Liz diciendo ""pixelitos"" https://t.c...",es,...,['https://pbs.twimg.com/media/E_3BR9HUUAgGzdN....,1,0,2,[],[],https://twitter.com/skellewe/status/1440519973...,1,US,[]
4,1440519973609242628,1440456923707424768,2021-09-22 03:34:59+00:00,2021-09-22,03:34:59,813245849417515008,alex_k_89,Alex,@Chuck_zw @MaximeBernier I'm going to post thi...,en,...,[],0,1,3,[],[],https://twitter.com/Alex_K_89/status/144051997...,0,US,"[{'screen_name': 'Chuck_zw', 'name': 'StandFor..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187072,1440514731471634441,1437961867054379008,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,35020995,shamgarreport,Terry McDermott,@ClearLikeWater1 @nwa @Jeez215 @AustinIdol @ty...,en,...,[],0,1,2,[],[],https://twitter.com/shamgarreport/status/14405...,0,US,"[{'screen_name': 'ClearLikeWater1', 'name': 'J..."
187073,1440514731450634243,1440514731450634240,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,1119277376108683264,clankapp,ClankApp - Crypto Whales Tracker üê≥,"üí∞25,216 #BSV (3,473,860 USD) move from multipl...",en,...,[],0,0,0,"['bsv', 'bitcoinsv', 'bsv']",[],https://twitter.com/ClankApp/status/1440514731...,0,US,[]
187074,1440514731400302601,1440511169874169856,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,251582751,ahedog,german ahedo,@DeMemoria Sue√±os de fuga,es,...,[],0,0,0,[],[],https://twitter.com/AhedoG/status/144051473140...,0,US,"[{'screen_name': 'DeMemoria', 'name': 'DeMemor..."
187075,1440514731379355649,1440397766027464704,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,1258972328970481665,99problmsince99,üß∏,@tujefateama same bro,en,...,[],0,0,0,[],[],https://twitter.com/99problmsince99/status/144...,0,US,"[{'screen_name': 'tujefateama', 'name': 'la ma..."
187076,1440514731354177536,1440298876057964544,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,1171030345732493312,carlosg85040080,Carlos Gutierrez Salcedo,@Pajaropolitico @Conacyt_MX Y ahora cuales son...,es,...,[],0,0,0,[],[],https://twitter.com/CarlosG85040080/status/144...,0,US,"[{'screen_name': 'Pajaropolitico', 'name': 'An..."

In [108]:
len(data['language'].unique())

57

we only want english tweets, i'll remove tne ones in other languages

In [117]:
data.drop(data[data['language'] != 'en'].index, inplace = True)

In [118]:
data.shape

(123173, 22)

In [119]:
data['language'].unique()

array(['en'], dtype=object)

In [121]:
len(data['photos'].unique())

12112

In [123]:
len(data['username'].unique())

80734

In [124]:
data['likes_count'].max()

34421

In [128]:
data.sort_values('likes_count', axis=0, ascending=False)

,id,conversation_id,created_at,date,time,user_id,username,name,tweet,language,...,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,link,video,near,reply_to
8116,1440519739810336778,1440519739810336768,2021-09-22 03:34:04+00:00,2021-09-22,03:34:04,1350868812216852485,chrissychlapp,chrissy chlapecka,hot people think that they‚Äôre dying every time...,en,...,[],81,3187,34421,[],[],https://twitter.com/chrissychlapp/status/14405...,0,US,[]
19043,1440519424209940493,1440519424209940480,2021-09-22 03:32:48+00:00,2021-09-22,03:32:48,1402376699644243971,_tmcjab,3,this a weird thing to say bout someone you‚Äôre ...,en,...,[],184,3853,24323,[],[],https://twitter.com/_TMCJab/status/14405194242...,0,US,[]
131054,1440516259754364936,1440516259754364928,2021-09-22 03:20:14+00:00,2021-09-22,03:20:14,1105963209801064448,wordtomae,Jane Redcorn,women with gaps be so sexy i just wanna slide ...,en,...,[],346,2135,19900,[],[],https://twitter.com/wordtoMae/status/144051625...,0,US,[]
125153,1440516426364637193,1440516426364637184,2021-09-22 03:20:54+00:00,2021-09-22,03:20:54,237875746,_colebennett_,Cole Bennett,ok soooooo ski said yes to catch me outside pa...,en,...,[],319,1507,19363,[],[],https://twitter.com/_ColeBennett_/status/14405...,0,US,[]
147178,1440515817200709634,1440515817200709632,2021-09-22 03:18:28+00:00,2021-09-22,03:18:28,18382184,adamparkhomenko,Adam Parkhomenko,One of the most devastating campaign ads and h...,en,...,[],259,6766,18544,[],[],https://twitter.com/AdamParkhomenko/status/144...,1,US,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118309,1440516619323654159,1440461878216380416,2021-09-22 03:21:40+00:00,2021-09-22,03:21:40,1233786593158152194,koachise,Dee,@jacobiiss Nothing less boss.,en,...,[],0,0,0,[],[],https://twitter.com/Koachise/status/1440516619...,0,US,"[{'screen_name': 'jacobiiss', 'name': '¬¢ob', '..."
118312,1440516619290099717,1440516619290099712,2021-09-22 03:21:40+00:00,2021-09-22,03:21:40,44233345,yates5,Sandra Yates,"@StephenKing Happy Birthday, happy happy birth...",en,...,[],0,0,0,[],[],https://twitter.com/Yates5/status/144051661929...,0,US,[]
118314,1440516619243962375,1440516619243962368,2021-09-22 03:21:40+00:00,2021-09-22,03:21:40,180365358,carolinawx,"Clayton, NC Weather",#WeatherbitAPI 16-day Wind Forecast Trends. h...,en,...,['https://pbs.twimg.com/media/E_2-OLVUUAMzfct....,0,0,0,['weatherbitapi'],[],https://twitter.com/CarolinaWx/status/14405166...,1,US,[]
49772,1440518568689291273,1440122714413469696,2021-09-22 03:29:24+00:00,2021-09-22,03:29:24,257255419,ejhinojosa,EJ Hinojosa,@njburkett7 @ABC7NY Did he not bring a bicycle?,en,...,[],0,0,0,[],[],https://twitter.com/ejhinojosa/status/14405185...,0,US,"[{'screen_name': 'njburkett7', 'name': 'N. J. ..."
187075,1440514731379355649,1440397766027464704,2021-09-22 03:14:10+00:00,2021-09-22,03:14:10,1258972328970481665,99problmsince99,üß∏,@tujefateama same bro,en,...,[],0,0,0,[],[],https://twitter.com/99problmsince99/status/144...,0,US,"[{'screen_name': 'tujefateama', 'name': 'la ma..."